version: '3.8'

services:
    back:
        container_name: back
        build: ./back/
        command: ./back
        depends_on:
            - mongo
        ports: 
            - 8080:8080
        environment:
            - PORT=8080
            - MONGO_URI=mongodb://mongo:27017/caloriesdb

    mongo: 
        restart: always
        image: mongo:latest
        container_name: mongodb
        volumes: 
            - apiDB:/data/db
        ports:
            - 27017:27017
        expose:
            - 27017

    
    front: 
        container_name: front
        restart: always
        build: ./front
        ports:
            - "3000:3000"
        depends_on:
            - back
    

volumes:
    apiDB: